### PR TITLE
Adding config for uvdar cams

### PR DESCRIPTION
**Pull request by ViktorWalter**

### CODE REVIEW

**Comment by spurnvoj** [comment]
@ViktorWalter Does it make sense to have it as part of this driver? You need to have a modified version of the launch file. What about the calibration file for every camera with tf publisher with its placement? Maybe those all can be part of some meta package for uvdar. Because this is specific for it.  Any thoughts on this?

**Comment by ViktorWalter** [comment]
You may be right. I'm not sure how widely used will these cameras be among us yet.

**Comment by spurnvoj** [comment]
@DanHert, what are your thoughts? How is it done now in the new MRS system? I expect this driver to be used with several different cameras for different purposes.

**Comment by DanHert** [comment]
We have camera calibrations in a different repo (mrs_uav_deployment) along with other stuff like platform configs, world files, etc.

**Comment by spurnvoj** [comment]
In https://github.com/ctu-mrs/libcamera_ros/pull/10, I extended `uav.launch` to accept `custom_config` argument. So you can store the config anywhere you want and pass the path to it as the argument. The custom config file can override the default parameters and add new ones.

**Comment by spurnvoj** [comment]
Therefore, I am closing this PR.

**Pull request closed without merging**
